import { collection, collectionGroup, doc, endAt, getDoc, getDocs, limit, onSnapshot, orderBy, query, runTransaction, serverTimestamp, startAt, Timestamp, updateDoc, where, writeBatch } from 'firebase/firestore'
import { db, getCurrentUser } from './firebase'
import { createCommunityPostNotification, removeCommunityPostNotification } from './notifications'

export const COMMUNITY_CATEGORIES = ['general', 'franchise', 'genre', 'movie', 'tv', 'director', 'actor', 'animation']
export const COMMUNITY_THEMES = ['sunset', 'nebula', 'noir', 'forest', 'ocean', 'crimson']
const now = () => serverTimestamp()
const clean = (value) => String(value || '').trim().replace(/\s+/g, ' ')
const actor = () => { const user = getCurrentUser(); if (!user) throw communityError('Topluluk işlemi için giriş yapmalısın.', 'community/unauthenticated'); return user }
function communityError(message, code = 'community/error') { const error = new Error(message); error.code = code; return error }
function mapError(error, stage, diagnostics = {}) {
  if (error?.code?.startsWith('community/')) return error
  if (import.meta.env.DEV) console.error(`[community:${stage}]`, { code: error?.code, message: error?.message, ...diagnostics })
  const code = String(error?.code || '').replace('firestore/', '')
  const messages = {
    'permission-denied': 'Bu topluluk içeriğine erişim iznin yok.',
    'failed-precondition': 'Topluluk gönderileri şu anda yüklenemiyor.',
    unavailable: 'Bağlantı kurulamadı. Lütfen tekrar dene.'
  }
  return communityError(messages[code] || 'Topluluk işlemi tamamlanamadı.', error?.code)
}

function validateCommunity(input) {
  const name = clean(input.name); const description = clean(input.description); const rules = clean(input.rules)
  if (name.length < 3 || name.length > 50) throw communityError('Topluluk adı 3–50 karakter olmalı.', 'community/invalid-name')
  if (description.length < 10 || description.length > 500) throw communityError('Açıklama 10–500 karakter olmalı.', 'community/invalid-description')
  if (rules.length > 1000) throw communityError('Topluluk kuralları en fazla 1000 karakter olabilir.', 'community/invalid-rules')
  if (!COMMUNITY_CATEGORIES.includes(input.category)) throw communityError('Geçerli bir kategori seçmelisin.', 'community/invalid-category')
  if (!COMMUNITY_THEMES.includes(input.theme)) throw communityError('Geçerli bir tema seçmelisin.', 'community/invalid-theme')
  return { name, nameLower: name.toLocaleLowerCase('tr-TR'), description, rules, category: input.category, theme: input.theme }
}

export async function createCommunity(input) { const user = actor(); const data = validateCommunity(input); const ref = doc(collection(db, 'communities')); const memberRef = doc(ref, 'members', user.uid); try { const batch = writeBatch(db); batch.set(ref, { ownerUid: user.uid, ...data, isPublic: true, isArchived: false, memberCount: 1, postCount: 0, createdAt: now(), updatedAt: now() }); batch.set(memberRef, { uid: user.uid, role: 'owner', createdAt: now(), updatedAt: now() }); await batch.commit(); return ref.id } catch (error) { throw mapError(error, 'create') } }
export async function searchCommunities(value, count = 20) { const normalized = clean(value).toLocaleLowerCase('tr-TR'); if (normalized.length < 2) return []; try { const snap = await getDocs(query(collection(db, 'communities'), orderBy('nameLower'), startAt(normalized), endAt(`${normalized}\uf8ff`), limit(Math.min(count, 20)))); return snap.docs.map((item) => ({ id: item.id, ...item.data() })).filter((item) => item.isPublic && !item.isArchived) } catch (error) { throw mapError(error, 'search') } }
export function subscribeToCommunities(onChange, onError) { return onSnapshot(query(collection(db, 'communities'), where('isPublic', '==', true), limit(50)), (snap) => onChange(snap.docs.map((item) => ({ id: item.id, ...item.data() })).filter((item) => !item.isArchived)), (error) => onError?.(mapError(error, 'list'))) }
export function subscribeToCommunity(id, onChange, onError) { return onSnapshot(doc(db, 'communities', id), (snap) => onChange(snap.exists() ? { id: snap.id, ...snap.data() } : null), (error) => onError?.(mapError(error, 'read'))) }
export function subscribeToMembers(id, onChange, onError) { return onSnapshot(query(collection(db, 'communities', id, 'members'), limit(100)), (snap) => onChange(snap.docs.map((item) => ({ id: item.id, ...item.data() }))), (error) => onError?.(mapError(error, 'members'))) }
export function subscribeToMembership(id, uid, onChange, onError) { if (!uid) { onChange(null); return () => {} } return onSnapshot(doc(db, 'communities', id, 'members', uid), (snap) => onChange(snap.exists() ? snap.data() : null), (error) => onError?.(mapError(error, 'membership'))) }
export async function getMyCommunityMemberships(uid) { if (!uid) return []; try { const snap = await getDocs(query(collectionGroup(db, 'members'), where('uid', '==', uid), limit(100))); return snap.docs.filter((item) => item.ref.parent.parent?.parent?.id === 'communities').map((item) => ({ communityId: item.ref.parent.parent.id, ...item.data() })) } catch (error) { throw mapError(error, 'memberships') } }
export async function getUserCommunities(uid, count = 6) { const memberships = await getMyCommunityMemberships(uid); const selected = memberships.slice(0, Math.min(count, 12)); const items = await Promise.all(selected.map(async (membership) => { const snap = await getDoc(doc(db, 'communities', membership.communityId)); return snap.exists() && snap.data().isPublic ? { id: snap.id, ...snap.data(), membership } : null })); return items.filter(Boolean) }
export async function joinCommunity(id) { const user = actor(); const communityRef = doc(db, 'communities', id); const memberRef = doc(communityRef, 'members', user.uid); try { await runTransaction(db, async (tx) => { const [communitySnap, memberSnap] = await Promise.all([tx.get(communityRef), tx.get(memberRef)]); if (!communitySnap.exists() || communitySnap.data().isArchived) throw communityError('Bu topluluğa şu anda katılamazsın.', 'community/unavailable'); if (memberSnap.exists()) return; tx.set(memberRef, { uid: user.uid, role: 'member', createdAt: now(), updatedAt: now() }); tx.update(communityRef, { memberCount: (communitySnap.data().memberCount || 0) + 1, updatedAt: now() }) }) } catch (error) { throw mapError(error, 'join') } }
export async function leaveCommunity(id) { const user = actor(); const communityRef = doc(db, 'communities', id); const memberRef = doc(communityRef, 'members', user.uid); try { await runTransaction(db, async (tx) => { const [communitySnap, memberSnap] = await Promise.all([tx.get(communityRef), tx.get(memberRef)]); if (!memberSnap.exists()) return; if (communitySnap.data().ownerUid === user.uid) throw communityError('Topluluk sahibi doğrudan ayrılamaz.', 'community/owner-cannot-leave'); tx.delete(memberRef); tx.update(communityRef, { memberCount: Math.max(0, (communitySnap.data().memberCount || 0) - 1), updatedAt: now() }) }) } catch (error) { throw mapError(error, 'leave') } }
export async function updateCommunity(id, input) { actor(); const data = validateCommunity(input); try { await updateDoc(doc(db, 'communities', id), { ...data, updatedAt: now() }) } catch (error) { throw mapError(error, 'update') } }
export async function setCommunityArchived(id, isArchived) { actor(); try { await updateDoc(doc(db, 'communities', id), { isArchived: Boolean(isArchived), updatedAt: now() }) } catch (error) { throw mapError(error, 'archive') } }
export async function setMemberRole(id, uid, role) { actor(); if (!['member', 'moderator'].includes(role)) throw communityError('Geçersiz topluluk rolü.'); try { await updateDoc(doc(db, 'communities', id, 'members', uid), { role, updatedAt: now() }) } catch (error) { throw mapError(error, 'role') } }
export async function removeMember(id, uid) { actor(); const communityRef = doc(db, 'communities', id); const memberRef = doc(communityRef, 'members', uid); try { await runTransaction(db, async (tx) => { const [communitySnap, memberSnap] = await Promise.all([tx.get(communityRef), tx.get(memberRef)]); if (!memberSnap.exists()) return; if (communitySnap.data().ownerUid === uid) throw communityError('Topluluk sahibi çıkarılamaz.'); tx.delete(memberRef); tx.update(communityRef, { memberCount: Math.max(0, communitySnap.data().memberCount - 1), updatedAt: now() }) }) } catch (error) { throw mapError(error, 'member-remove') } }
export async function transferOwnership(id, nextUid) { const user = actor(); const communityRef = doc(db, 'communities', id); const oldRef = doc(communityRef, 'members', user.uid); const nextRef = doc(communityRef, 'members', nextUid); try { await runTransaction(db, async (tx) => { const [communitySnap, oldSnap, nextSnap] = await Promise.all([tx.get(communityRef), tx.get(oldRef), tx.get(nextRef)]); if (!communitySnap.exists() || communitySnap.data().ownerUid !== user.uid || !oldSnap.exists() || !nextSnap.exists() || nextUid === user.uid) throw communityError('Sahiplik aktarımı yapılamadı.'); tx.update(communityRef, { ownerUid: nextUid, updatedAt: now() }); tx.update(oldRef, { role: 'moderator', updatedAt: now() }); tx.update(nextRef, { role: 'owner', updatedAt: now() }) }) } catch (error) { throw mapError(error, 'transfer') } }

export function subscribeToCommunityPosts(id, onChange, onError) { return onSnapshot(query(collection(db, 'communities', id, 'posts'), orderBy('createdAt', 'desc'), limit(100)), (snap) => onChange(snap.docs.map((item) => ({ id: item.id, ...item.data() }))), (error) => onError?.(mapError(error, 'posts'))) }
export function subscribeToCommunityFeed(communityIds, onChange, onError, options = {}) {
  const selectedIds = [...new Set((communityIds || []).filter(Boolean))].slice(0, Math.min(options.maxCommunities || 12, 12))
  const perCommunityLimit = Math.min(Math.max(options.perCommunityLimit || 6, 1), 10)
  if (!selectedIds.length) { onChange([]); return () => {} }

  const postsByCommunity = new Map()
  let active = true
  const emit = () => {
    if (!active) return
    const millis = (value) => typeof value?.toMillis === 'function' ? value.toMillis() : (value?.seconds || 0) * 1000
    onChange([...postsByCommunity.values()].flat().sort((a, b) => millis(b.createdAt) - millis(a.createdAt)))
  }
  const stops = selectedIds.map((communityId) => onSnapshot(
    query(collection(db, 'communities', communityId, 'posts'), orderBy('createdAt', 'desc'), limit(perCommunityLimit)),
    (snapshot) => {
      postsByCommunity.set(communityId, snapshot.docs.map((item) => ({ id: item.id, communityId, ...item.data() })))
      emit()
    },
    (error) => onError?.(mapError(error, 'feed', {
      purpose: 'joined-community-posts',
      activeUid: getCurrentUser()?.uid || null,
      collection: `communities/${communityId}/posts`,
      filters: [],
      orderBy: 'createdAt desc',
      limit: perCommunityLimit
    }))
  ))

  return () => {
    active = false
    stops.forEach((stop) => stop())
  }
}
export async function createCommunityPost(id, input) { const user = actor(); const content = clean(input.content); if (content.length < 1 || content.length > 1000) throw communityError('Gönderi 1–1000 karakter olmalı.'); const communityRef = doc(db, 'communities', id); const postRef = doc(collection(communityRef, 'posts')); const media = input.media || null; try { await runTransaction(db, async (tx) => { const communitySnap = await tx.get(communityRef); const memberSnap = await tx.get(doc(communityRef, 'members', user.uid)); if (!communitySnap.exists() || communitySnap.data().isArchived || !memberSnap.exists()) throw communityError('Gönderi paylaşmak için aktif topluluğa katılmalısın.'); tx.set(postRef, { communityId: id, ownerUid: user.uid, type: 'discussion', content, spoiler: Boolean(input.spoiler), mediaKey: media ? `${media.media_type}_${media.id}` : null, mediaType: media?.media_type || null, mediaId: media ? String(media.id) : null, mediaTitle: media?.title || media?.name || null, posterPath: media?.poster_path || null, pollId: null, likeCount: 0, replyCount: 0, isPinned: false, createdAt: now(), updatedAt: now() }); tx.update(communityRef, { postCount: (communitySnap.data().postCount || 0) + 1, updatedAt: now() }) }); return postRef.id } catch (error) { throw mapError(error, 'post-create') } }
export async function toggleCommunityPostLike(id, postId, active) { const user = actor(); const postRef = doc(db, 'communities', id, 'posts', postId); const likeRef = doc(postRef, 'likes', user.uid); let ownerUid = ''; let changed = false; try { await runTransaction(db, async (tx) => { const [postSnap, likeSnap, communitySnap, memberSnap] = await Promise.all([tx.get(postRef), tx.get(likeRef), tx.get(doc(db, 'communities', id)), tx.get(doc(db, 'communities', id, 'members', user.uid))]); if (!postSnap.exists() || !memberSnap.exists() || communitySnap.data().isArchived) throw communityError('Bu gönderiyle etkileşim kuramazsın.'); ownerUid = postSnap.data().ownerUid; if (active && !likeSnap.exists()) { changed = true; tx.set(likeRef, { uid: user.uid, createdAt: now() }); tx.update(postRef, { likeCount: (postSnap.data().likeCount || 0) + 1, updatedAt: now() }) } else if (!active && likeSnap.exists()) { changed = true; tx.delete(likeRef); tx.update(postRef, { likeCount: Math.max(0, (postSnap.data().likeCount || 0) - 1), updatedAt: now() }) } }); if (changed && ownerUid !== user.uid) { try { if (active) await createCommunityPostNotification({ recipientUid: ownerUid, type: 'community_post_like', communityId: id, postId }); else await removeCommunityPostNotification({ recipientUid: ownerUid, type: 'community_post_like', communityId: id, postId, actorUid: user.uid }) } catch (notificationError) { if (import.meta.env.DEV) console.warn('[community:post-like-notification]', notificationError); return { warning: 'Beğeni kaydedildi ancak bildirim gönderilemedi.' } } } return { changed } } catch (error) { throw mapError(error, 'post-like') } }
export function subscribeToPostLike(id, postId, uid, onChange) { if (!uid) { onChange(false); return () => {} } return onSnapshot(doc(db, 'communities', id, 'posts', postId, 'likes', uid), (snap) => onChange(snap.exists()), () => onChange(false)) }
export function subscribeToReplies(id, postId, onChange, onError) { return onSnapshot(query(collection(db, 'communities', id, 'posts', postId, 'replies'), orderBy('createdAt', 'asc'), limit(100)), (snap) => onChange(snap.docs.map((item) => ({ id: item.id, ...item.data() }))), (error) => onError?.(mapError(error, 'replies'))) }
export async function createCommunityReply(id, postId, content, spoiler = false) { const user = actor(); const text = clean(content); if (text.length < 1 || text.length > 500) throw communityError('Cevap 1–500 karakter olmalı.'); const postRef = doc(db, 'communities', id, 'posts', postId); const replyRef = doc(collection(postRef, 'replies')); let ownerUid = ''; try { await runTransaction(db, async (tx) => { const [postSnap, communitySnap, memberSnap] = await Promise.all([tx.get(postRef), tx.get(doc(db, 'communities', id)), tx.get(doc(db, 'communities', id, 'members', user.uid))]); if (!postSnap.exists() || !memberSnap.exists() || communitySnap.data().isArchived) throw communityError('Cevap yazmak için aktif topluluğa katılmalısın.'); ownerUid = postSnap.data().ownerUid; tx.set(replyRef, { ownerUid: user.uid, content: text, spoiler: Boolean(spoiler), createdAt: now(), updatedAt: now() }); tx.update(postRef, { replyCount: (postSnap.data().replyCount || 0) + 1, lastReplyId: replyRef.id, updatedAt: now() }) }); let warning = ''; if (ownerUid !== user.uid) try { await createCommunityPostNotification({ recipientUid: ownerUid, type: 'community_post_reply', communityId: id, postId, replyId: replyRef.id }) } catch (notificationError) { if (import.meta.env.DEV) console.warn('[community:reply-notification]', notificationError); warning = 'Cevap kaydedildi ancak bildirim gönderilemedi.' } return { id: replyRef.id, warning } } catch (error) { throw mapError(error, 'reply-create') } }
export async function deleteCommunityReply(id, postId, replyId) { const user = actor(); const postRef = doc(db, 'communities', id, 'posts', postId); const replyRef = doc(postRef, 'replies', replyId); let ownerUid = ''; let replyOwnerUid = ''; try { await runTransaction(db, async (tx) => { const [postSnap, replySnap] = await Promise.all([tx.get(postRef), tx.get(replyRef)]); if (!replySnap.exists()) return; ownerUid = postSnap.data().ownerUid; replyOwnerUid = replySnap.data().ownerUid; tx.delete(replyRef); tx.update(postRef, { replyCount: Math.max(0, (postSnap.data().replyCount || 0) - 1), lastReplyId: replyId, updatedAt: now() }) }); if (ownerUid && ownerUid !== replyOwnerUid) try { await removeCommunityPostNotification({ recipientUid: ownerUid, type: 'community_post_reply', communityId: id, postId, actorUid: replyOwnerUid || user.uid, replyId }) } catch (notificationError) { if (import.meta.env.DEV) console.warn('[community:reply-notification-delete]', notificationError) } } catch (error) { throw mapError(error, 'reply-delete') } }
export async function setPostPinned(id, postId, pinned) { actor(); try { await updateDoc(doc(db, 'communities', id, 'posts', postId), { isPinned: Boolean(pinned), updatedAt: now() }) } catch (error) { throw mapError(error, 'pin') } }
export async function deleteCommunityPost(id, postId) { actor(); const communityRef = doc(db, 'communities', id); const postRef = doc(communityRef, 'posts', postId); try { await runTransaction(db, async (tx) => { const [communitySnap, postSnap] = await Promise.all([tx.get(communityRef), tx.get(postRef)]); if (!postSnap.exists()) return; tx.delete(postRef); tx.update(communityRef, { postCount: Math.max(0, (communitySnap.data().postCount || 0) - 1), updatedAt: now() }) }) } catch (error) { throw mapError(error, 'post-delete') } }
export async function createCommunityPoll(id, input) { const user = actor(); const question = clean(input.question); const options = (input.options || []).map(clean).filter(Boolean); if (question.length < 3 || question.length > 160) throw communityError('Anket sorusu 3–160 karakter olmalı.'); if (options.length < 2 || options.length > 4 || options.some((item) => item.length > 80) || new Set(options).size !== options.length) throw communityError('Anket 2–4 farklı ve geçerli seçenek içermeli.'); const communityRef = doc(db, 'communities', id); const pollRef = doc(collection(communityRef, 'polls')); const postRef = doc(collection(communityRef, 'posts')); const days = Number(input.durationDays || 0); const closesAt = days ? Timestamp.fromMillis(Date.now() + days * 86400000) : null; try { await runTransaction(db, async (tx) => { const [communitySnap, memberSnap] = await Promise.all([tx.get(communityRef), tx.get(doc(communityRef, 'members', user.uid))]); if (!communitySnap.exists() || communitySnap.data().isArchived || !memberSnap.exists()) throw communityError('Anket oluşturmak için topluluğa katılmalısın.'); tx.set(pollRef, { communityId: id, postId: postRef.id, ownerUid: user.uid, question, options, optionCounts: options.map(() => 0), totalVotes: 0, closesAt, createdAt: now(), updatedAt: now() }); tx.set(postRef, { communityId: id, ownerUid: user.uid, type: 'poll', content: question, spoiler: Boolean(input.spoiler), mediaKey: null, mediaType: null, mediaId: null, mediaTitle: null, posterPath: null, pollId: pollRef.id, likeCount: 0, replyCount: 0, isPinned: false, createdAt: now(), updatedAt: now() }); tx.update(communityRef, { postCount: (communitySnap.data().postCount || 0) + 1, updatedAt: now() }) }); return postRef.id } catch (error) { throw mapError(error, 'poll-create') } }
export function subscribeToPoll(id, pollId, onChange, onError) { if (!pollId) { onChange(null); return () => {} } return onSnapshot(doc(db, 'communities', id, 'polls', pollId), (snap) => onChange(snap.exists() ? { id: snap.id, ...snap.data() } : null), (error) => onError?.(mapError(error, 'poll'))) }
export function subscribeToVote(id, pollId, uid, onChange) { if (!uid || !pollId) { onChange(null); return () => {} } return onSnapshot(doc(db, 'communities', id, 'polls', pollId, 'votes', uid), (snap) => onChange(snap.exists() ? snap.data() : null), () => onChange(null)) }
export async function voteCommunityPoll(id, pollId, optionIndex) { const user = actor(); const pollRef = doc(db, 'communities', id, 'polls', pollId); const voteRef = doc(pollRef, 'votes', user.uid); try { await runTransaction(db, async (tx) => { const [communitySnap, memberSnap, pollSnap, voteSnap] = await Promise.all([tx.get(doc(db, 'communities', id)), tx.get(doc(db, 'communities', id, 'members', user.uid)), tx.get(pollRef), tx.get(voteRef)]); if (!memberSnap.exists() || communitySnap.data().isArchived || !pollSnap.exists() || voteSnap.exists()) throw communityError('Bu ankete oy veremezsin.'); const poll = pollSnap.data(); if (poll.closesAt?.toMillis?.() <= Date.now() || !Number.isInteger(optionIndex) || optionIndex < 0 || optionIndex >= poll.options.length) throw communityError('Anket sona erdi veya seçenek geçersiz.'); const counts = [...poll.optionCounts]; counts[optionIndex] += 1; tx.set(voteRef, { uid: user.uid, optionIndex, createdAt: now() }); tx.update(pollRef, { optionCounts: counts, totalVotes: poll.totalVotes + 1, updatedAt: now() }) }) } catch (error) { throw mapError(error, 'poll-vote') } }
export async function updateCommunityPost(id, postId, input) { const user = actor(); const content = clean(input.content); if (content.length < 1 || content.length > 1000) throw communityError('Gönderi 1–1000 karakter olmalı.'); const media = input.media || null; try { await updateDoc(doc(db, 'communities', id, 'posts', postId), { content, spoiler: Boolean(input.spoiler), mediaKey: media ? `${media.media_type}_${media.id}` : null, mediaType: media?.media_type || null, mediaId: media ? String(media.id) : null, mediaTitle: media?.title || media?.name || null, posterPath: media?.poster_path || null, updatedAt: now() }) } catch (error) { throw mapError(error, 'post-update') } }
