import { addDoc, collection, deleteDoc, doc, onSnapshot, serverTimestamp, Timestamp, updateDoc } from 'firebase/firestore'
import { db } from './firebase'

function diaryError(error){const code=String(error?.code||'').replace(/^firestore\//,'');const messages={'permission-denied':'Bu günlük işlemini yapmaya yetkiniz yok.',unauthenticated:'Günlük işlemi için giriş yapmalısınız.',unavailable:'Günlük servisine şu anda ulaşılamıyor. Lütfen tekrar deneyin.','deadline-exceeded':'Günlük işlemi zaman aşımına uğradı.'};const mapped=new Error(messages[code]||error?.message||'Günlük işlemi tamamlanamadı.');mapped.code=error?.code||'diary/unknown';return mapped}
export function todayDateKey(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}
export function dateKeyToTimestamp(dateKey){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(dateKey||''));if(!match)throw new Error('Geçerli bir izleme tarihi seçin.');const date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]),12,0,0,0);if(date.getFullYear()!==Number(match[1])||date.getMonth()!==Number(match[2])-1||date.getDate()!==Number(match[3]))throw new Error('Geçerli bir izleme tarihi seçin.');return Timestamp.fromDate(date)}
export function timestampToDateKey(value){const date=typeof value?.toDate==='function'?value.toDate():value instanceof Date?value:null;if(!date)return '';return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function validate(input){if(!input.uid)throw new Error('Günlüğe eklemek için giriş yapmalısınız.');if(!['movie','tv'].includes(input.mediaType))throw new Error('Geçersiz medya türü.');const note=String(input.note||'').trim();if(Array.from(note).length>500)throw new Error('Kısa not en fazla 500 karakter olabilir.');const rating=input.rating===''||input.rating==null?null:Number(input.rating);if(rating!==null&&(!Number.isInteger(rating)||rating<1||rating>5))throw new Error('Puan 1–5 arasında tam sayı olmalı.');return{note,rating,watchedAt:dateKeyToTimestamp(input.watchedDate)}}
function millis(value){return typeof value?.toMillis==='function'?value.toMillis():typeof value?.seconds==='number'?value.seconds*1000:0}
export async function createDiaryEntry(input){const valid=validate(input);try{const mediaKey=`${input.mediaType}_${String(input.mediaId)}`;const ref=await addDoc(collection(db,'users',input.uid,'diary'),{uid:input.uid,mediaKey,mediaId:String(input.mediaId),mediaType:input.mediaType,title:String(input.title||''),posterPath:String(input.posterPath||''),releaseDate:String(input.releaseDate||''),watchedAt:valid.watchedAt,rating:valid.rating,rewatch:Boolean(input.rewatch),note:valid.note,tags:[],visibility:'private',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});let activityWarning='';if(input.shareToFeed){try{const{createActivity}=await import('./activities');await createActivity({uid:input.uid,type:'watched',targetType:'diary',targetId:ref.id,mediaKey})}catch(activityError){activityWarning='Diary kaydı oluşturuldu ancak aktivite akışında paylaşılamadı.';if(import.meta.env.DEV)console.error('[activity:diary-create]',{code:activityError.code,message:activityError.message,activityId:activityError.activityId,payload:activityError.payload})}}return{id:ref.id,activityWarning}}catch(error){throw diaryError(error)}}
export async function updateDiaryEntry(uid,entryId,values){const valid=validate({uid,mediaType:values.mediaType||'movie',...values});try{await updateDoc(doc(db,'users',uid,'diary',entryId),{watchedAt:valid.watchedAt,rating:valid.rating,rewatch:Boolean(values.rewatch),note:valid.note,updatedAt:serverTimestamp()});let activityWarning='';if(typeof values.shareToFeed==='boolean'){try{const activities=await import('./activities');const exists=await activities.hasActivity('watched',entryId);if(values.shareToFeed&&!exists)await activities.createActivity({uid,type:'watched',targetType:'diary',targetId:entryId,mediaKey:values.mediaKey||''});if(!values.shareToFeed&&exists)await activities.deleteActivity(uid,'watched',entryId)}catch(activityError){activityWarning='Günlük kaydı güncellendi ancak aktivite paylaşımı eşitlenemedi.';if(import.meta.env.DEV)console.error('[activity:diary-update]',{code:activityError.code,message:activityError.message,activityId:activityError.activityId,payload:activityError.payload})}}return{activityWarning}}catch(error){throw diaryError(error)}}
export async function deleteDiaryEntry(uid,entryId){try{await deleteDoc(doc(db,'users',uid,'diary',entryId));try{const{deleteActivity}=await import('./activities');await deleteActivity(uid,'watched',entryId)}catch(activityError){console.warn('Günlük kaydı silindi ancak aktivitesi kaldırılamadı.',activityError)}}catch(error){throw diaryError(error)}}
export function subscribeToUserDiary(uid,onChange,onError){if(!uid){onChange([]);return()=>{}}return onSnapshot(collection(db,'users',uid,'diary'),snapshot=>onChange(snapshot.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>millis(b.watchedAt)-millis(a.watchedAt)||millis(b.createdAt)-millis(a.createdAt))),error=>onError?.(diaryError(error)))}
