import { collection, deleteDoc, doc, onSnapshot, query, serverTimestamp, setDoc, where } from 'firebase/firestore'
import { db, getCurrentUser } from './firebase'
import { getProfileByUid } from './profile'

function followError(error){const code=String(error?.code||'').replace(/^firestore\//,'');const messages={'permission-denied':'Bu takip işlemini yapmaya yetkiniz yok.',unauthenticated:'Takip etmek için giriş yapmalısınız.',unavailable:'Takip bilgilerine şu anda ulaşılamıyor.'};return new Error(messages[code]||error?.message||'Takip işlemi tamamlanamadı.')}
export function followId(followerUid,followingUid){return `${followerUid}_${followingUid}`}
function assertActor(followerUid,followingUid){const current=getCurrentUser();if(!current||current.uid!==followerUid)throw new Error('Takip işlemi için kendi hesabınızla giriş yapmalısınız.');if(!followingUid||followerUid===followingUid)throw new Error('Kendinizi takip edemezsiniz.')}
export async function followUser(followerUid,followingUid){assertActor(followerUid,followingUid);try{await setDoc(doc(db,'follows',followId(followerUid,followingUid)),{followerUid,followingUid,createdAt:serverTimestamp()});try{const{createNotification}=await import('./notifications');await createNotification({recipientUid:followingUid,type:'follow',targetType:'user',targetId:followerUid})}catch(notificationError){if(import.meta.env.DEV)console.error('[notification:follow-create]',notificationError);return{warning:'İşlem tamamlandı ancak bildirim gönderilemedi.'}}return{warning:''}}catch(error){throw followError(error)}}
export async function unfollowUser(followerUid,followingUid){assertActor(followerUid,followingUid);try{await deleteDoc(doc(db,'follows',followId(followerUid,followingUid)));try{const{removeNotification}=await import('./notifications');await removeNotification({recipientUid:followingUid,type:'follow',targetId:followerUid,actorUid:followerUid})}catch(notificationError){if(import.meta.env.DEV)console.error('[notification:follow-delete]',notificationError)}}catch(error){throw followError(error)}}
export function subscribeToFollowStatus(followerUid,followingUid,onChange,onError){if(!followerUid||!followingUid||followerUid===followingUid){onChange(false);return()=>{}}return onSnapshot(doc(db,'follows',followId(followerUid,followingUid)),snap=>onChange(snap.exists()),error=>onError?.(followError(error)))}
function subscribeRelations(field,uid,onChange,onError){return onSnapshot(query(collection(db,'follows'),where(field,'==',uid)),snap=>onChange(snap.docs.map(item=>({id:item.id,...item.data()}))),error=>onError?.(followError(error)))}
export const subscribeToFollowers=(uid,onChange,onError)=>subscribeRelations('followingUid',uid,onChange,onError)
export const subscribeToFollowing=(uid,onChange,onError)=>subscribeRelations('followerUid',uid,onChange,onError)
export async function attachFollowProfiles(relations,field){return Promise.all(relations.map(async relation=>({...relation,profile:await getProfileByUid(relation[field]).catch(()=>null)})))}
