import { collection, doc, getDoc, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc, where, writeBatch } from 'firebase/firestore'
import { db, getCurrentUser } from './firebase'
import { getProfileByUid } from './profile'

function messageError(error,fallback='Mesaj işlemi tamamlanamadı.'){const code=String(error?.code||'').replace(/^firestore\//,'');const messages={'permission-denied':'Bu konuşmayı görüntüleme veya mesaj gönderme yetkiniz yok.',unauthenticated:'Mesajlaşmak için giriş yapmalısınız.',unavailable:'Mesaj servisine şu anda ulaşılamıyor.','not-found':'Konuşma bulunamadı.'};const result=new Error(messages[code]||error?.message||fallback);result.code=code||'unknown';return result}
function assertActor(uid){const current=getCurrentUser();if(!current||current.uid!==uid)throw new Error('Mesaj işlemi için kendi hesabınızla giriş yapmalısınız.')}
export function conversationIdFor(firstUid,secondUid){if(!firstUid||!secondUid||firstUid===secondUid)throw new Error('Kendinize mesaj gönderemezsiniz.');return [firstUid,secondUid].sort().join('_')}
function millis(value){return typeof value?.toMillis==='function'?value.toMillis():typeof value?.seconds==='number'?value.seconds*1000:0}
export async function findConversation(firstUid,secondUid){const id=conversationIdFor(firstUid,secondUid);try{const snap=await getDoc(doc(db,'conversations',id));return snap.exists()?{id:snap.id,...snap.data()}:null}catch(error){throw messageError(error)}}
export async function getConversation(conversationId){if(!conversationId)return null;try{const snap=await getDoc(doc(db,'conversations',conversationId));return snap.exists()?{id:snap.id,...snap.data()}:null}catch(error){throw messageError(error)}}
export async function ensureConversation(senderUid,otherUid){assertActor(senderUid);const participants=[senderUid,otherUid].sort();const id=conversationIdFor(senderUid,otherUid);const ref=doc(db,'conversations',id);try{await setDoc(ref,{participants,createdBy:senderUid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return id}catch(createError){try{const snap=await getDoc(ref);if(!snap.exists())throw createError;const existingParticipants=snap.data().participants;if(!Array.isArray(existingParticipants)||existingParticipants.length!==2||!participants.every(uid=>existingParticipants.includes(uid)))throw new Error('Bu konuşma kimliği başka bir konuşmayla eşleşiyor.');return id}catch(readError){const source=readError?.message==='Bu konuşma kimliği başka bir konuşmayla eşleşiyor.'?readError:createError;const mapped=messageError(source,'Konuşma başlatılamadı.');if(mapped.code==='permission-denied')throw new Error('Konuşma başlatılamadı. Bu işlem için yetkiniz yok.');throw mapped}}}
export async function sendMessage(conversationId,senderUid,content,otherUid){assertActor(senderUid);const text=String(content||'').trim();if(!text||Array.from(text).length>1000)throw new Error('Mesaj 1–1000 karakter arasında olmalı.');let id=conversationId;let messageId='';let recipientUid='';try{if(!id)id=await ensureConversation(senderUid,otherUid);const conversationRef=doc(db,'conversations',id);const conversation=await getDoc(conversationRef);const participants=conversation.exists()?conversation.data().participants:null;if(!Array.isArray(participants)||!participants.includes(senderUid))throw new Error('Bu konuşmaya mesaj gönderemezsiniz.');if(participants.length!==2){if(import.meta.env.DEV)console.error('[notification:message-upsert]',{code:'messages/invalid-participants',message:'Birebir konuşma tam olarak iki katılımcı içermeli.',conversationId:id,participants});throw new Error('Bu konuşmanın katılımcı yapısı birebir mesajlaşmaya uygun değil.')}recipientUid=participants.find(uid=>uid!==senderUid)||'';const messageRef=doc(collection(conversationRef,'messages'));messageId=messageRef.id;const batch=writeBatch(db);batch.set(messageRef,{senderUid,content:text,mediaUrl:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.update(conversationRef,{lastMessageId:messageId,lastSenderUid:senderUid,lastMessageAt:serverTimestamp(),updatedAt:serverTimestamp()});await batch.commit()}catch(error){throw messageError(error)}try{if(recipientUid&&recipientUid!==senderUid){const{upsertMessageNotification}=await import('./notifications');await upsertMessageNotification({recipientUid,conversationId:id,messageId})}}catch(notificationError){if(import.meta.env.DEV)console.error('[notification:message-upsert]',{code:notificationError?.code,message:notificationError?.message,conversationId:id,messageId,recipientUid});return{conversationId:id,messageId,warning:'Mesaj gönderildi ancak bildirim oluşturulamadı.'}}return{conversationId:id,messageId,warning:''}}
export function subscribeToConversations(uid,onChange,onError){if(!uid){onChange([]);return()=>{}}return onSnapshot(query(collection(db,'conversations'),where('participants','array-contains',uid)),snap=>onChange(snap.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>millis(b.updatedAt)-millis(a.updatedAt))),error=>onError?.(messageError(error)))}
export function subscribeToMessages(conversationId,count,onChange,onError){if(!conversationId){onChange([]);return()=>{}}return onSnapshot(query(collection(db,'conversations',conversationId,'messages'),orderBy('createdAt','desc'),limit(count)),snap=>onChange(snap.docs.map(item=>({id:item.id,...item.data()})).reverse()),error=>onError?.(messageError(error)))}
export async function attachConversationProfiles(conversations,currentUid){return Promise.all(conversations.map(async conversation=>{const otherUid=conversation.participants.find(uid=>uid!==currentUid);return{...conversation,otherUid,otherProfile:await getProfileByUid(otherUid).catch(()=>null)}}))}
