import { collection, collectionGroup, deleteDoc, doc, getDoc, onSnapshot, query, serverTimestamp, setDoc, where, writeBatch } from 'firebase/firestore'
import { db, getCurrentUser } from './firebase'

function safetyError(error){const code=String(error?.code||'').replace(/^firestore\//,'');const messages={'permission-denied':'Bu güvenlik işlemini yapmaya yetkiniz yok.',unauthenticated:'Bu işlem için giriş yapmalısınız.',unavailable:'Güvenlik servisine şu anda ulaşılamıyor.'};return new Error(messages[code]||error?.message||'Güvenlik işlemi tamamlanamadı.')}
function assertActor(uid,targetUid){const current=getCurrentUser();if(!current||current.uid!==uid)throw new Error('Bu işlem için kendi hesabınızla giriş yapmalısınız.');if(!targetUid||uid===targetUid)throw new Error('Kendi hesabınız için bu işlemi yapamazsınız.')}
function preferenceRef(uid,type,targetUid){return doc(db,'users',uid,type,targetUid)}
async function setPreference(uid,type,targetUid,active){assertActor(uid,targetUid);try{const ref=preferenceRef(uid,type,targetUid);if(active)await setDoc(ref,{targetUid,createdAt:serverTimestamp()});else await deleteDoc(ref)}catch(error){throw safetyError(error)}}
export async function setUserBlocked(uid,targetUid,active){assertActor(uid,targetUid);if(!active)return setPreference(uid,'blocks',targetUid,false);try{const outgoingRef=doc(db,'follows',`${uid}_${targetUid}`);const incomingRef=doc(db,'follows',`${targetUid}_${uid}`);const[outgoing,incoming]=await Promise.all([getDoc(outgoingRef),getDoc(incomingRef)]);const batch=writeBatch(db);batch.set(preferenceRef(uid,'blocks',targetUid),{targetUid,createdAt:serverTimestamp()});if(outgoing.exists())batch.delete(outgoingRef);if(incoming.exists())batch.delete(incomingRef);await batch.commit()}catch(error){throw safetyError(error)}}
export const setUserMuted=(uid,targetUid,active)=>setPreference(uid,'mutes',targetUid,active)
export async function isBlockedEitherWay(uid,targetUid){assertActor(uid,targetUid);try{const [outbound,inbound]=await Promise.all([getDoc(preferenceRef(uid,'blocks',targetUid)),getDoc(preferenceRef(targetUid,'blocks',uid))]);return outbound.exists()||inbound.exists()}catch(error){throw safetyError(error)}}
function subscribePreferences(uid,type,onChange,onError){if(!uid){onChange([]);return()=>{}}return onSnapshot(collection(db,'users',uid,type),snap=>onChange(snap.docs.map(item=>({id:item.id,...item.data()}))),error=>onError?.(safetyError(error)))}
export const subscribeToBlocks=(uid,onChange,onError)=>subscribePreferences(uid,'blocks',onChange,onError)
export const subscribeToMutes=(uid,onChange,onError)=>subscribePreferences(uid,'mutes',onChange,onError)
export function subscribeToBlockedBy(uid,onChange,onError){if(!uid){onChange([]);return()=>{}}return onSnapshot(query(collectionGroup(db,'blocks'),where('targetUid','==',uid)),snap=>onChange(snap.docs.map(item=>({id:item.id,blockerUid:item.ref.parent.parent?.id||''})).filter(item=>item.blockerUid)),error=>onError?.(safetyError(error)))}
