import { useEffect, useRef, useState } from 'react'
import { searchMulti } from '../../services/tmdb'
import { getTmdbImageUrl, toYear } from '../../services/tmdbHelpers'

export function MediaPickerModal({ onSelect, onClose }) {
  const [query,setQuery]=useState(''); const [results,setResults]=useState([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const inputRef=useRef(null); const requestId=useRef(0)
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';inputRef.current?.focus();const key=(event)=>{if(event.key==='Escape')onClose()};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key)}},[onClose])
  useEffect(()=>{const value=query.trim();const currentRequest=++requestId.current;if(value.length<2){setResults([]);setLoading(false);setError('');return}const timer=setTimeout(async()=>{setLoading(true);setError('');try{const data=await searchMulti(value);if(requestId.current===currentRequest)setResults((data.results||[]).filter(item=>['movie','tv'].includes(item.media_type)))}catch(e){if(requestId.current===currentRequest)setError(e.message)}finally{if(requestId.current===currentRequest)setLoading(false)}},350);return()=>clearTimeout(timer)},[query])
  return <div className="social-modal-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose()}}><section className="social-media-modal" role="dialog" aria-modal="true" aria-labelledby="media-picker-title"><header><h3 id="media-picker-title">Film veya dizi seç</h3><button type="button" onClick={onClose} aria-label="Pencereyi kapat">×</button></header><label className="social-search-label"><span>Yapım ara</span><input ref={inputRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="En az 2 karakter yaz" /></label><div className="social-media-results">{loading?<p>Aranıyor…</p>:error?<p className="auth-message auth-message-error">{error}</p>:results.length?results.map(item=>{const title=item.title||item.name||item.original_title||item.original_name;return <button type="button" key={`${item.media_type}-${item.id}`} onClick={()=>onSelect(item)}><span className="social-result-poster">{item.poster_path?<img src={getTmdbImageUrl(item.poster_path,'w92')} alt=""/>:<span>L</span>}</span><span><strong>{title}</strong><small>{toYear(item.release_date||item.first_air_date)} · {item.media_type==='tv'?'Dizi':'Film'}</small></span></button>}):<p>{query.trim().length<2?'Aramak için en az iki karakter yaz.':'Sonuç bulunamadı.'}</p>}</div></section></div>
}
