import { useEffect, useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { CommunityPostCard } from '../components/communities/CommunityPostCard'
import { EmptyState } from '../components/shared/EmptyState'
import { SpoilerContent } from '../components/shared/SpoilerContent'
import { UserAvatar } from '../components/shared/UserAvatar'
import { useAuth } from '../context/AuthContext'
import { createCommunityReply, deleteCommunityReply, subscribeToCommunity, subscribeToCommunityPosts, subscribeToMembership, subscribeToReplies } from '../services/communities'
import { getProfileByUid } from '../services/profile'
import { PrimaryButton } from '../design-system'

export function CommunityPostDetailPage() { const { communityId, postId } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [community, setCommunity] = useState(); const [post, setPost] = useState(); const [membership, setMembership] = useState(null); const [replies, setReplies] = useState([]); const [profiles, setProfiles] = useState({}); const [content, setContent] = useState(''); const [spoiler, setSpoiler] = useState(false); const [pending, setPending] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => subscribeToCommunity(communityId, setCommunity, (e) => setError(e.message)), [communityId]); useEffect(() => subscribeToCommunityPosts(communityId, (items) => { setPost(items.find((item) => item.id === postId) || null); setLoading(false) }, (e) => { setError(e.message); setLoading(false) }), [communityId, postId]); useEffect(() => subscribeToMembership(communityId, user?.uid, setMembership, (e) => setError(e.message)), [communityId, user?.uid]); useEffect(() => subscribeToReplies(communityId, postId, setReplies, (e) => setError(e.message)), [communityId, postId])
  useEffect(() => { const uids = [...new Set([post?.ownerUid, ...replies.map((item) => item.ownerUid)].filter(Boolean))]; let active = true; Promise.all(uids.map(async (uid) => [uid, await getProfileByUid(uid).catch(() => null)])).then((items) => { if (active) setProfiles(Object.fromEntries(items)) }); return () => { active = false } }, [post?.ownerUid, replies.map((item) => item.ownerUid).join('|')])
  const submit = async (event) => { event.preventDefault(); if (!user) { navigate('/login', { state: { from: location.pathname } }); return }; setPending('reply'); setError(''); try { await createCommunityReply(communityId, postId, content, spoiler); setContent(''); setSpoiler(false) } catch (e) { setError(e.message) } finally { setPending('') } }
  const remove = async (replyId) => { setPending(replyId); try { await deleteCommunityReply(communityId, postId, replyId) } catch (e) { setError(e.message) } finally { setPending('') } }
  if (loading) return <div className="list-loading">Gönderi yükleniyor…</div>; if (!post || !community) return <EmptyState title="Gönderi bulunamadı" message="Gönderi silinmiş veya erişilemiyor."/>
  return <div className="page-stack"><Link to={`/communities/${communityId}`}>← {community.name}</Link><CommunityPostCard community={community} post={post} profile={profiles[post.ownerUid]} membership={membership} detail/><section className="profile-section-card"><h2>Cevaplar</h2>{membership && !community.isArchived ? <form className="community-reply-form" onSubmit={submit}><textarea value={content} onChange={(e) => setContent(e.target.value)} maxLength={500} placeholder="Cevabını yaz…" required/><div><span>{content.length}/500</span><label><input type="checkbox" checked={spoiler} onChange={(e) => setSpoiler(e.target.checked)}/> Spoiler</label><PrimaryButton type="submit" disabled={pending === 'reply'}>{pending === 'reply' ? 'Gönderiliyor…' : 'Cevapla'}</PrimaryButton></div></form> : <p>Yanıtlamak için topluluğa katıl.</p>}{error ? <p className="auth-message auth-message-error">{error}</p> : null}<div className="community-replies">{replies.map((reply) => { const profile = profiles[reply.ownerUid]; const canDelete = user?.uid === reply.ownerUid || ['owner', 'moderator'].includes(membership?.role); return <article key={reply.id}><header><Link to={profile?.username ? `/profile/${encodeURIComponent(profile.username)}` : '#'}><UserAvatar profile={profile} name={profile?.username || 'Kullanıcı'} className="avatar-sm"/><strong>{profile?.username || 'Luma kullanıcısı'}</strong></Link>{canDelete ? <button type="button" disabled={pending === reply.id} onClick={() => remove(reply.id)}>Sil</button> : null}</header><SpoilerContent id={reply.id} spoiler={reply.spoiler} warning="Bu cevap spoiler içeriyor.">{reply.content}</SpoilerContent></article> })}</div></section></div> }
