import { useState } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { COMMUNITY_CATEGORIES, COMMUNITY_THEMES, createCommunity } from '../services/communities'
import { CATEGORY_LABELS } from '../components/communities/CommunityCard'
import { PrimaryButton } from '../design-system'

export function CommunityCreatePage() { const { user, authLoading } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ name: '', description: '', category: 'general', theme: 'sunset', rules: '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); if (authLoading) return <div className="list-loading">Oturum kontrol ediliyor…</div>; if (!user) return <Navigate to="/login" replace state={{ from: location.pathname }}/>
  const submit = async (event) => { event.preventDefault(); if (saving) return; setSaving(true); setError(''); try { const id = await createCommunity(form); navigate(`/communities/${id}`, { replace: true }) } catch (e) { setError(e.message) } finally { setSaving(false) } }
  return <div className="page-stack"><section className={`community-page-hero community-theme-${form.theme}`}><p className="eyebrow">Yeni topluluk</p><h1>{form.name || 'Topluluğunun adı'}</h1><p>Herkese açık bir Luma buluşma alanı oluştur.</p></section><section className="profile-section-card"><form className="community-create-form" onSubmit={submit}><label>Topluluk adı<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} minLength={3} maxLength={50} required /></label><label>Açıklama<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} minLength={10} maxLength={500} required /></label><label>Kategori<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{COMMUNITY_CATEGORIES.map((value) => <option key={value} value={value}>{CATEGORY_LABELS[value]}</option>)}</select></label><label>Görsel tema<select value={form.theme} onChange={(e) => setForm({ ...form, theme: e.target.value })}>{COMMUNITY_THEMES.map((value) => <option key={value}>{value}</option>)}</select></label><label>Topluluk kuralları<textarea value={form.rules} onChange={(e) => setForm({ ...form, rules: e.target.value })} maxLength={1000}/></label><p className="report-notice">Bu sürümde bütün topluluklar herkese açıktır.</p>{error ? <p className="auth-message auth-message-error">{error}</p> : null}<PrimaryButton type="submit" disabled={saving}>{saving ? 'Oluşturuluyor…' : 'Topluluğu oluştur'}</PrimaryButton></form></section></div> }
