import { useEffect, useState } from 'react'
import { Navigate, useNavigate, useParams } from 'react-router-dom'
import { CATEGORY_LABELS } from '../components/communities/CommunityCard'
import { UserAvatar } from '../components/shared/UserAvatar'
import { useAuth } from '../context/AuthContext'
import { COMMUNITY_CATEGORIES, COMMUNITY_THEMES, removeMember, setCommunityArchived, setMemberRole, subscribeToCommunity, subscribeToMembers, transferOwnership, updateCommunity } from '../services/communities'
import { getProfileByUid } from '../services/profile'
import { PrimaryButton, SecondaryButton } from '../design-system'

export function CommunitySettingsPage() { const { communityId } = useParams(); const { user, authLoading } = useAuth(); const navigate = useNavigate(); const [community, setCommunity] = useState(); const [members, setMembers] = useState([]); const [profiles, setProfiles] = useState({}); const [form, setForm] = useState(null); const [pending, setPending] = useState(''); const [message, setMessage] = useState(''); useEffect(() => subscribeToCommunity(communityId, (item) => { setCommunity(item); if (item) setForm({ name: item.name, description: item.description, rules: item.rules, category: item.category, theme: item.theme }) }, (e) => setMessage(e.message)), [communityId]); useEffect(() => subscribeToMembers(communityId, setMembers, (e) => setMessage(e.message)), [communityId]); useEffect(() => { let active = true; Promise.all(members.map(async (item) => [item.uid, await getProfileByUid(item.uid).catch(() => null)])).then((items) => { if (active) setProfiles(Object.fromEntries(items)) }); return () => { active = false } }, [members.map((item) => item.uid).join('|')]); if (authLoading || !community || !form) return <div className="list-loading">Ayarlar yükleniyor…</div>; if (!user || community.ownerUid !== user.uid) return <Navigate to={`/communities/${communityId}`} replace/>
  const save = async (event) => { event.preventDefault(); setPending('save'); setMessage(''); try { await updateCommunity(communityId, form); setMessage('Topluluk ayarları güncellendi.') } catch (e) { setMessage(e.message) } finally { setPending('') } }; const action = async (key, work) => { setPending(key); setMessage(''); try { await work() } catch (e) { setMessage(e.message) } finally { setPending('') } }
  return <div className="page-stack"><section className={`community-page-hero community-theme-${form.theme}`}><p className="eyebrow">Topluluk yönetimi</p><h1>{community.name}</h1><button type="button" onClick={() => navigate(`/communities/${communityId}`)}>Topluluğa dön</button></section><section className="profile-section-card"><h2>Ayarlar</h2><form className="community-create-form" onSubmit={save}><label>Topluluk adı<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} minLength={3} maxLength={50}/></label><label>Açıklama<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} minLength={10} maxLength={500}/></label><label>Kurallar<textarea value={form.rules} onChange={(e) => setForm({ ...form, rules: e.target.value })} maxLength={1000}/></label><label>Kategori<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{COMMUNITY_CATEGORIES.map((value) => <option key={value} value={value}>{CATEGORY_LABELS[value]}</option>)}</select></label><label>Tema<select value={form.theme} onChange={(e) => setForm({ ...form, theme: e.target.value })}>{COMMUNITY_THEMES.map((value) => <option key={value}>{value}</option>)}</select></label><PrimaryButton type="submit" disabled={pending === 'save'}>{pending === 'save' ? 'Kaydediliyor…' : 'Kaydet'}</PrimaryButton></form><hr/><SecondaryButton onClick={() => { if (window.confirm(community.isArchived ? 'Topluluğu yeniden etkinleştirmek istiyor musun?' : 'Topluluğu arşivlemek istiyor musun?')) action('archive', () => setCommunityArchived(communityId, !community.isArchived)) }}>{community.isArchived ? 'Arşivden çıkar' : 'Topluluğu arşivle'}</SecondaryButton>{message ? <p className="auth-message">{message}</p> : null}</section><section className="profile-section-card"><h2>Üyeleri yönet</h2><div className="community-member-management">{members.map((member) => { const profile = profiles[member.uid]; return <article key={member.uid}><UserAvatar profile={profile} name={profile?.username || 'Kullanıcı'} className="avatar-sm"/><strong>{profile?.username || 'Luma kullanıcısı'}</strong><span>{member.role}</span>{member.role !== 'owner' ? <div><button onClick={() => action(member.uid, () => setMemberRole(communityId, member.uid, member.role === 'moderator' ? 'member' : 'moderator'))}>{member.role === 'moderator' ? 'Üye yap' : 'Moderatör yap'}</button><button onClick={() => action(member.uid, () => removeMember(communityId, member.uid))}>Çıkar</button><button onClick={() => { if (window.confirm('Sahipliği bu üyeye devretmek istediğine emin misin?')) action(member.uid, () => transferOwnership(communityId, member.uid)) }}>Sahipliği devret</button></div> : null}</article> })}</div></section></div> }
