import { useEffect, useMemo, useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { CommunityPostCard } from '../components/communities/CommunityPostCard'
import { CommunityPollComposer } from '../components/communities/CommunityPollComposer'
import { CATEGORY_LABELS } from '../components/communities/CommunityCard'
import { MediaPickerModal } from '../components/social/MediaPickerModal'
import { ReportModal } from '../components/reports/ReportModal'
import { EmptyState } from '../components/shared/EmptyState'
import { UserAvatar } from '../components/shared/UserAvatar'
import { useAuth } from '../context/AuthContext'
import { useSafety } from '../context/SafetyContext'
import { createCommunityPost, joinCommunity, leaveCommunity, subscribeToCommunity, subscribeToCommunityPosts, subscribeToMembers } from '../services/communities'
import { getProfileByUid } from '../services/profile'
import { PrimaryButton, SecondaryButton } from '../design-system'

export function CommunityDetailPage() {
  const { communityId } = useParams(); const { user } = useAuth(); const safety = useSafety(); const navigate = useNavigate(); const location = useLocation()
  const [community, setCommunity] = useState(); const [members, setMembers] = useState([]); const [posts, setPosts] = useState([]); const [profiles, setProfiles] = useState({}); const [tab, setTab] = useState('feed'); const [sort, setSort] = useState('new'); const [composerType, setComposerType] = useState('post'); const [content, setContent] = useState(''); const [spoiler, setSpoiler] = useState(false); const [media, setMedia] = useState(null); const [picker, setPicker] = useState(false); const [reportOpen, setReportOpen] = useState(false); const [pending, setPending] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => subscribeToCommunity(communityId, (item) => { setCommunity(item); setLoading(false) }, (e) => { setError(e.message); setLoading(false) }), [communityId])
  useEffect(() => subscribeToMembers(communityId, setMembers, (e) => setError(e.message)), [communityId])
  useEffect(() => subscribeToCommunityPosts(communityId, setPosts, (e) => setError(e.message)), [communityId])
  useEffect(() => { const uids = [...new Set([community?.ownerUid, ...members.map((item) => item.uid), ...posts.map((item) => item.ownerUid)].filter(Boolean))]; let active = true; Promise.all(uids.map(async (uid) => [uid, await getProfileByUid(uid).catch(() => null)])).then((items) => { if (active) setProfiles(Object.fromEntries(items)) }); return () => { active = false } }, [community?.ownerUid, members.map((item) => item.uid).join('|'), posts.map((item) => item.ownerUid).join('|')])
  const membership = members.find((item) => item.uid === user?.uid)
  const visiblePosts = useMemo(() => posts.filter((item) => !safety.blockedUids.has(item.ownerUid) && (!safety.mutedUids.has(item.ownerUid) || ['owner', 'moderator'].includes(membership?.role))).sort((a, b) => Number(b.isPinned) - Number(a.isPinned) || (sort === 'popular' ? (b.likeCount + b.replyCount) - (a.likeCount + a.replyCount) : (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0))), [posts, safety.blockedUids, safety.mutedUids, membership?.role, sort])
  const requireUser = () => { if (user) return true; navigate('/login', { state: { from: `${location.pathname}${location.search}` } }); return false }
  const toggleMembership = async () => { if (!requireUser()) return; setPending('membership'); setError(''); try { if (membership) await leaveCommunity(communityId); else await joinCommunity(communityId) } catch (e) { setError(e.message) } finally { setPending('') } }
  const publish = async (event) => { event.preventDefault(); if (!membership || pending) return; setPending('post'); setError(''); try { await createCommunityPost(communityId, { content, spoiler, media }); setContent(''); setSpoiler(false); setMedia(null) } catch (e) { setError(e.message) } finally { setPending('') } }
  if (loading || safety.loading) return <div className="list-loading">Topluluk yükleniyor…</div>
  if (!community) return <EmptyState title="Topluluk bulunamadı" message="Bu topluluğu görüntüleme yetkin yok."/>
  return <div className="page-stack">
    <section className={`community-page-hero community-theme-${community.theme}`}>
      <div className="community-hero-letter">{community.name.charAt(0).toLocaleUpperCase('tr-TR')}</div><p className="eyebrow">{CATEGORY_LABELS[community.category]}</p><h1>{community.name}</h1><p>{community.description}</p>
      <div className="community-real-meta"><span>{community.memberCount || 0} üye</span><span>{community.postCount || 0} gönderi</span>{membership ? <span>{membership.role === 'owner' ? 'Sahip' : membership.role === 'moderator' ? 'Moderatör' : 'Üye'}</span> : null}</div>
      {community.isArchived ? <p className="auth-message">Bu topluluk arşivlendi.</p> : <div className="community-hero-actions">{membership?.role === 'owner' ? <Link className="ds-button ds-button-secondary" to={`/communities/${communityId}/settings`}>Topluluk ayarları</Link> : <SecondaryButton onClick={toggleMembership} disabled={pending === 'membership'}>{membership ? 'Topluluktan ayrıl' : 'Topluluğa katıl'}</SecondaryButton>}{user?.uid !== community.ownerUid ? <SecondaryButton onClick={() => requireUser() && setReportOpen(true)}>Topluluğu şikâyet et</SecondaryButton> : null}</div>}
    </section>
    <section className="profile-section-card">
      <div className="community-tabs" role="tablist"><button className={tab === 'feed' ? 'active' : ''} onClick={() => setTab('feed')}>Akış</button><button className={tab === 'about' ? 'active' : ''} onClick={() => setTab('about')}>Hakkında</button><button className={tab === 'members' ? 'active' : ''} onClick={() => setTab('members')}>Üyeler</button></div>
      {error ? <p className="auth-message auth-message-error">{error}</p> : null}
      {tab === 'feed' ? <><div className="community-feed-sort"><button className={sort === 'new' ? 'active' : ''} onClick={() => setSort('new')}>En yeni</button><button className={sort === 'popular' ? 'active' : ''} onClick={() => setSort('popular')}>Popüler</button></div>{membership && !community.isArchived ? <><div className="community-composer-tabs"><button className={composerType === 'post' ? 'active' : ''} onClick={() => setComposerType('post')}>Gönderi</button><button className={composerType === 'poll' ? 'active' : ''} onClick={() => setComposerType('poll')}>Anket</button></div>{composerType === 'poll' ? <CommunityPollComposer communityId={communityId} onCancel={() => setComposerType('post')}/> : <form className="community-composer" onSubmit={publish}><textarea value={content} onChange={(e) => setContent(e.target.value)} maxLength={1000} placeholder="Toplulukla bir şey paylaş…" required/><div><span>{content.length}/1000</span><label><input type="checkbox" checked={spoiler} onChange={(e) => setSpoiler(e.target.checked)}/> Spoiler</label><SecondaryButton type="button" onClick={() => setPicker(true)}>{media ? 'Yapımı değiştir' : 'Film/dizi ekle'}</SecondaryButton><PrimaryButton type="submit" disabled={pending === 'post'}>{pending === 'post' ? 'Yayınlanıyor…' : 'Yayınla'}</PrimaryButton></div>{media ? <p>Eklenen yapım: <strong>{media.title || media.name}</strong> <button type="button" onClick={() => setMedia(null)}>Kaldır</button></p> : null}</form>}</> : <p className="community-join-notice">{community.isArchived ? 'Bu topluluk arşivlendi.' : 'Gönderi paylaşmak için topluluğa katıl.'}</p>}{visiblePosts.length ? <div className="community-post-list">{visiblePosts.map((post) => <CommunityPostCard key={post.id} community={community} post={post} profile={profiles[post.ownerUid]} membership={membership}/>)}</div> : <EmptyState title="Bu toplulukta henüz gönderi paylaşılmadı." message="İlk sohbeti üyeler başlatabilir."/>}</> : tab === 'about' ? <div className="community-about"><h2>Topluluk kuralları</h2><p>{community.rules || 'Henüz özel bir topluluk kuralı eklenmedi.'}</p><h3>Topluluk sahibi</h3><Link to={profiles[community.ownerUid]?.username ? `/profile/${profiles[community.ownerUid].username}` : '#'}>{profiles[community.ownerUid]?.username || 'Luma kullanıcısı'}</Link></div> : <div className="community-members">{members.map((member) => { const memberProfile = profiles[member.uid]; return <Link key={member.uid} to={memberProfile?.username ? `/profile/${encodeURIComponent(memberProfile.username)}` : '#'}><UserAvatar profile={memberProfile} name={memberProfile?.username || 'Kullanıcı'} className="avatar-sm"/><span>{memberProfile?.username || 'Luma kullanıcısı'}</span><small>{member.role === 'owner' ? 'Sahip' : member.role === 'moderator' ? 'Moderatör' : 'Üye'}</small></Link> })}</div>}
    </section>
    {picker ? <MediaPickerModal onSelect={(item) => { setMedia(item); setPicker(false) }} onClose={() => setPicker(false)}/> : null}
    {reportOpen ? <ReportModal targetType="community" targetId={communityId} onClose={() => setReportOpen(false)}/> : null}
  </div>
}
