import { useEffect, useMemo, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { CommunityCard, CATEGORY_LABELS } from '../components/communities/CommunityCard'
import { EmptyState } from '../components/shared/EmptyState'
import { useAuth } from '../context/AuthContext'
import { useSafety } from '../context/SafetyContext'
import { getMyCommunityMemberships, joinCommunity, leaveCommunity, subscribeToCommunities } from '../services/communities'

export function CommunitiesPage() {
  const { user, authLoading } = useAuth(); const safety = useSafety(); const navigate = useNavigate(); const location = useLocation(); const [communities, setCommunities] = useState([]); const [memberships, setMemberships] = useState([]); const [tab, setTab] = useState('discover'); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [sort, setSort] = useState('members'); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(''); const [error, setError] = useState('')
  useEffect(() => subscribeToCommunities((items) => { setCommunities(items); setLoading(false) }, (e) => { setError(e.message); setLoading(false) }), [])
  useEffect(() => { if (authLoading || !user) { setMemberships([]); return }; getMyCommunityMemberships(user.uid).then(setMemberships).catch((e) => setError(e.message)) }, [authLoading, user?.uid])
  const membershipMap = useMemo(() => Object.fromEntries(memberships.map((item) => [item.communityId, item])), [memberships])
  const visible = useMemo(() => communities.filter((item) => !safety.blockedUids.has(item.ownerUid)).filter((item) => tab === 'discover' || (tab === 'joined' && membershipMap[item.id]) || (tab === 'managed' && ['owner', 'moderator'].includes(membershipMap[item.id]?.role))).filter((item) => !search || item.nameLower?.includes(search.trim().toLocaleLowerCase('tr-TR'))).filter((item) => !category || item.category === category).sort((a, b) => sort === 'new' ? (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0) : (b.memberCount || 0) - (a.memberCount || 0)), [communities, membershipMap, tab, search, category, sort, safety.blockedUids])
  const requireUser = () => { if (user) return true; navigate('/login', { state: { from: `${location.pathname}${location.search}` } }); return false }
  const join = async (id) => { if (!requireUser()) return; setPending(id); setError(''); try { await joinCommunity(id); setMemberships(await getMyCommunityMemberships(user.uid)) } catch (e) { setError(e.message) } finally { setPending('') } }
  const leave = async (id) => { setPending(id); setError(''); try { await leaveCommunity(id); setMemberships(await getMyCommunityMemberships(user.uid)) } catch (e) { setError(e.message) } finally { setPending('') } }
  return <div className="page-stack"><section className="community-page-hero community-theme-nebula"><p className="eyebrow">Luma Toplulukları</p><h1>Birlikte izle, tartış, keşfet.</h1><p>Sevdiğin filmler, diziler ve sinema insanları etrafında gerçek topluluklara katıl.</p><Link className="ds-button ds-button-primary" to={user ? '/communities/new' : '/login'} state={!user ? { from: '/communities/new' } : undefined}>Yeni topluluk oluştur</Link></section><section className="card-section"><div className="community-tabs" role="tablist"><button className={tab === 'discover' ? 'active' : ''} onClick={() => setTab('discover')}>Keşfet</button><button className={tab === 'joined' ? 'active' : ''} onClick={() => setTab('joined')}>Katıldıklarım</button><button className={tab === 'managed' ? 'active' : ''} onClick={() => setTab('managed')}>Yönettiklerim</button></div><div className="community-filters"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Topluluk ara" aria-label="Topluluk ara"/><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Tüm kategoriler</option>{Object.entries(CATEGORY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="members">Üye sayısı</option><option value="new">En yeni</option></select></div>{error ? <p className="auth-message auth-message-error">{error}</p> : null}{loading ? <div className="list-loading">Topluluklar yükleniyor…</div> : visible.length ? <div className="community-grid">{visible.map((item) => <CommunityCard key={item.id} community={item} membership={membershipMap[item.id]} pending={pending} onJoin={join} onLeave={leave}/>)}</div> : <EmptyState title={tab === 'joined' ? 'Henüz bir topluluğa katılmadın.' : 'Henüz topluluk yok.'} message="Film ve dizi sohbetleri burada başlayacak."/>}</section></div>
}
