import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PrimaryButton } from '../design-system'
import { SocialFeed } from '../components/social/SocialFeed'
import { MyCommunitiesFeed } from '../components/communities/MyCommunitiesFeed'
import { useAuth } from '../context/AuthContext'
import { subscribeToFollowing } from '../services/follows'

export function FeedPage() { const { user } = useAuth(); const [count, setCount] = useState(20); const [tab, setTab] = useState('all'); const [following, setFollowing] = useState([]); useEffect(() => user?.uid ? subscribeToFollowing(user.uid, setFollowing, () => {}) : undefined, [user?.uid]); const ownerUids = useMemo(() => user ? [user.uid, ...following.map((item) => item.followingUid)] : [], [following, user?.uid]); return <div className="page-stack"><section className="discover-hero-card genre-hero"><p className="eyebrow">Topluluk</p><h1>Tüm akış</h1><p>Luma topluluğunun gerçek film ve dizi sohbetleri.</p></section><div className="media-tabs" role="tablist"><button role="tab" aria-selected={tab === 'all'} className={tab === 'all' ? 'active' : ''} onClick={() => setTab('all')}>Genel Akış</button><button role="tab" aria-selected={tab === 'following'} className={tab === 'following' ? 'active' : ''} onClick={() => setTab('following')}>Takip Ettiklerim</button><button role="tab" aria-selected={tab === 'communities'} className={tab === 'communities' ? 'active' : ''} onClick={() => setTab('communities')}>Topluluklarım</button></div>{tab === 'communities' ? <MyCommunitiesFeed/> : tab === 'following' && !user ? <section className="profile-section-card"><p>Takip akışını görmek için giriş yapmalısın.</p><Link className="primary-btn" to="/login" state={{ from: '/feed' }}>Giriş yap</Link></section> : tab === 'following' && following.length === 0 ? <section className="profile-section-card"><p>Takip ettiğin kullanıcıların gönderileri burada görünecek.</p><Link className="primary-btn" to="/discover">Kullanıcı önerilerine göz at</Link></section> : <SocialFeed title={false} limit={tab === 'all' ? count : undefined} ownerUids={tab === 'following' ? ownerUids : undefined}/>} {tab === 'all' ? <PrimaryButton onClick={() => setCount((value) => value + 20)}>Daha fazla göster</PrimaryButton> : null}</div> }
