import { useEffect,useState } from 'react'
import { Navigate,useLocation,useNavigate,useParams } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useSafety } from '../context/SafetyContext'
import { getProfileByUid,getProfileByUsername } from '../services/profile'
import { attachPostProfiles,subscribeToPublicPosts } from '../services/posts'
import { subscribeToUserReviews } from '../services/reviews'
import { subscribeToPublicLists } from '../services/lists'
import { attachFollowProfiles,followUser,subscribeToFollowers,subscribeToFollowing,subscribeToFollowStatus,unfollowUser } from '../services/follows'
import { ensureConversation } from '../services/messages'
import { PostCard } from '../components/social/PostCard'
import { ReviewCard } from '../components/reviews/ReviewCard'
import { ListCard } from '../components/lists/ListCard'
import { UserAvatar } from '../components/shared/UserAvatar'
import { EmptyState } from '../components/shared/EmptyState'
import { PageLoadingFallback } from '../components/shared/PageLoadingFallback'
import { FollowListModal } from '../components/profile/FollowListModal'
import { SafetyMenu } from '../components/safety/SafetyMenu'
import { PrimaryButton,SecondaryButton } from '../design-system'

export function PublicProfilePage(){const{username}=useParams();const{user,profile:ownProfile}=useAuth();const safety=useSafety();const navigate=useNavigate();const location=useLocation();const[profile,setProfile]=useState(null);const[loading,setLoading]=useState(true);const[posts,setPosts]=useState([]);const[reviews,setReviews]=useState([]);const[lists,setLists]=useState([]);const[followers,setFollowers]=useState([]);const[following,setFollowing]=useState([]);const[isFollowing,setIsFollowing]=useState(false);const[pending,setPending]=useState(false);const[error,setError]=useState('');const[listModal,setListModal]=useState('')
useEffect(()=>{let active=true;setLoading(true);getProfileByUsername(username).then(value=>active&&setProfile(value)).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[username])
useEffect(()=>{if(!profile?.uid)return;let active=true;let postRequest=0;const safeError=e=>{if(active)setError(e)};const stops=[subscribeToPublicPosts(async items=>{const request=++postRequest;const enriched=await attachPostProfiles(items.filter(item=>item.ownerUid===profile.uid));if(active&&request===postRequest)setPosts(enriched)},safeError),subscribeToUserReviews(profile.uid,items=>{if(active)setReviews(items)},safeError),subscribeToPublicLists(items=>{if(active)setLists(items.filter(item=>item.ownerUid===profile.uid))},safeError),subscribeToFollowers(profile.uid,items=>{if(active)setFollowers(items)},safeError),subscribeToFollowing(profile.uid,items=>{if(active)setFollowing(items)},safeError)];if(user?.uid)stops.push(subscribeToFollowStatus(user.uid,profile.uid,value=>{if(active)setIsFollowing(value)},safeError));return()=>{active=false;stops.forEach(stop=>stop?.())}},[profile?.uid,user?.uid])
if((user?.uid&&profile?.uid===user.uid)||(ownProfile?.username&&ownProfile.username.toLocaleLowerCase('tr-TR')===String(username).toLocaleLowerCase('tr-TR')))return <Navigate to="/profile" replace/>;if(loading)return <div className="list-loading">Profil yükleniyor…</div>;if(!profile)return <EmptyState title="Bu kullanıcı bulunamadı" message="Bu kullanıcı bulunamadı."/>
const toggle=async()=>{if(!user){navigate('/login',{state:{from:`${location.pathname}${location.search}`}});return}if(safety.isBlockedBy(profile.uid)){setError('Bu kullanıcıyla etkileşim kuramazsın.');return}setPending(true);setError('');try{let result;if(safety.isBlocked(profile.uid))await safety.unblock(profile.uid);else if(isFollowing)await unfollowUser(user.uid,profile.uid);else result=await followUser(user.uid,profile.uid);if(result?.warning)setError(result.warning)}catch(e){setError(e.message)}finally{setPending(false)}}
const openRelations=async type=>{const source=type==='followers'?followers:following;const field=type==='followers'?'followerUid':'followingUid';setListModal(type);try{const enriched=await attachFollowProfiles(source,field);if(type==='followers')setFollowers(enriched);else setFollowing(enriched)}catch(e){setError(e.message)}}
const startMessage=async()=>{if(!user){navigate('/login',{state:{from:`${location.pathname}${location.search}`}});return}if(safety.blockedUids.has(profile.uid)){setError('Bu kullanıcıyla mesajlaşamazsın.');return}setPending(true);setError('');try{const id=await ensureConversation(user.uid,profile.uid);navigate(`/messages/${id}`)}catch(e){setError(e.message||'Konuşma başlatılamadı.')}finally{setPending(false)}}
return <div className="page-stack"><section className="profile-hero-card public-profile-hero"><UserAvatar profile={profile} name={profile.username} className="profile-avatar"/><div className="public-profile-copy"><p className="eyebrow">Luma profili</p><h1>{profile.username}</h1>{profile.bio?<p>{profile.bio}</p>:null}<div className="public-follow-stats"><button onClick={()=>openRelations('followers')}><strong>{followers.length}</strong> Takipçi</button><button onClick={()=>openRelations('following')}><strong>{following.length}</strong> Takip</button></div></div><div className="public-profile-actions"><PrimaryButton onClick={toggle} disabled={pending}>{pending?'İşleniyor…':safety.isBlocked(profile.uid)?'Engeli kaldır':isFollowing?'Takiptesin':'Takip et'}</PrimaryButton>{!safety.isBlocked(profile.uid)?<SecondaryButton onClick={startMessage} disabled={pending}>Mesaj gönder</SecondaryButton>:null}<SafetyMenu targetUid={profile.uid} targetType="user" targetId={profile.uid}/></div></section>{error?<p className="auth-message auth-message-error">{error}</p>:null}<section className="profile-section-card"><h2>Gönderiler</h2>{posts.length?<div className="social-post-list">{posts.map(post=><PostCard key={post.id} post={post}/>)}</div>:<EmptyState title="Gönderiler boş" message="Henüz gönderi paylaşılmadı."/>}</section><section className="profile-section-card"><h2>Yorumlar</h2>{reviews.length?<div className="review-grid">{reviews.map(review=><ReviewCard key={review.id} review={{...review,authorProfile:profile}}/>)}</div>:<EmptyState title="Yorumlar boş" message="Henüz yorum paylaşılmadı."/>}</section><section className="profile-section-card"><h2>Herkese açık listeler</h2>{lists.length?<div className="review-grid">{lists.map(list=><ListCard key={list.id} list={{...list,authorProfile:profile}}/>)}</div>:<EmptyState title="Listeler boş" message="Henüz herkese açık liste yok."/>}</section>{listModal?<FollowListModal title={listModal==='followers'?'Takipçiler':'Takip edilenler'} items={listModal==='followers'?followers:following} empty={listModal==='followers'?'Henüz takipçisi yok.':'Henüz kimseyi takip etmiyor.'} onClose={()=>setListModal('')}/>:null}</div>}

export function LegacyUserProfileRedirect(){const{uid}=useParams();const[profile,setProfile]=useState(undefined);useEffect(()=>{let active=true;getProfileByUid(uid).then(value=>{if(active)setProfile(value)}).catch(()=>{if(active)setProfile(null)});return()=>{active=false}},[uid]);if(profile===undefined)return <PageLoadingFallback message="Profil yükleniyor…"/>;if(!profile)return <EmptyState title="Bu kullanıcı bulunamadı" message="Bu kullanıcı bulunamadı."/>;return <Navigate to={`/profile/${encodeURIComponent(profile.username)}`} replace/>}
