import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { PublicProfilePage } from './PublicProfilePage'
import { getProfileByUsername } from '../services/profile'
import { subscribeToLibraryPrivacy, subscribeToPublicLibrary } from '../services/libraryPrivacy'
import { getTmdbImageUrl } from '../services/tmdbHelpers'
import { ActivityFeed } from '../components/activity/ActivityFeed'
import { EmptyState } from '../components/shared/EmptyState'
import { UserCommunitiesSection } from '../components/communities/UserCommunitiesSection'

function PublicMediaSection({ title, open, items, loading, empty, hidden }) { return <section className="profile-section-card public-library-section"><div className="section-heading"><h2>{title}</h2>{open ? <span>{items.length}</span> : null}</div>{!open ? <EmptyState title={`${title} gizli`} message={hidden}/> : loading ? <div className="profile-library-skeleton"><span className="skeleton-card"/><span className="skeleton-card"/></div> : items.length ? <div className="profile-library-grid">{items.map((item) => <Link key={item.id} className="profile-library-card" to={`/${item.mediaType}/${item.mediaId}`}><div className="profile-library-poster">{item.posterPath ? <img src={getTmdbImageUrl(item.posterPath, 'w342')} alt={`${item.title} posteri`} loading="lazy"/> : <span>Luma</span>}</div><div className="profile-library-copy"><h3>{item.title || 'İsimsiz yapım'}</h3><p>{item.year || '—'}</p><span className="profile-media-type">{item.mediaType === 'tv' ? 'Dizi' : 'Film'}</span></div></Link>)}</div> : <EmptyState title={`${title} boş`} message={empty}/>}</section> }
export function PublicProfileWithActivityPage() { const { username } = useParams(); const [uid, setUid] = useState(''); const [settings, setSettings] = useState({ showFavorites: false, showWatched: false }); const [favorites, setFavorites] = useState([]); const [watched, setWatched] = useState([]); const [loading, setLoading] = useState({ favorite: false, watched: false }); useEffect(() => { let active = true; setUid(''); setSettings({ showFavorites: false, showWatched: false }); setFavorites([]); setWatched([]); getProfileByUsername(username).then((profile) => { if (active) setUid(profile?.uid || '') }).catch(() => {}); return () => { active = false } }, [username]); useEffect(() => uid ? subscribeToLibraryPrivacy(uid, setSettings, () => setSettings({ showFavorites: false, showWatched: false })) : undefined, [uid]); useEffect(() => { setFavorites([]); if (!uid || !settings.showFavorites) { setLoading((value) => ({ ...value, favorite: false })); return undefined } setLoading((value) => ({ ...value, favorite: true })); return subscribeToPublicLibrary(uid, 'favorite', (items) => { setFavorites(items); setLoading((value) => ({ ...value, favorite: false })) }, () => setLoading((value) => ({ ...value, favorite: false }))) }, [settings.showFavorites, uid]); useEffect(() => { setWatched([]); if (!uid || !settings.showWatched) { setLoading((value) => ({ ...value, watched: false })); return undefined } setLoading((value) => ({ ...value, watched: true })); return subscribeToPublicLibrary(uid, 'watched', (items) => { setWatched(items); setLoading((value) => ({ ...value, watched: false })) }, () => setLoading((value) => ({ ...value, watched: false }))) }, [settings.showWatched, uid]); return <><PublicProfilePage />{uid ? <><UserCommunitiesSection uid={uid} max={6}/><PublicMediaSection title="Favoriler" open={settings.showFavorites} items={favorites} loading={loading.favorite} empty="Henüz herkese açık bir favorisi yok." hidden="Favoriler gizli."/><PublicMediaSection title="İzlenenler" open={settings.showWatched} items={watched} loading={loading.watched} empty="Henüz herkese açık bir izleme kaydı yok." hidden="İzlenenler gizli."/><section className="profile-section-card public-profile-activity"><h2>Aktiviteler</h2><ActivityFeed mode="own" uid={uid} max={20}/></section></> : null}</> }
