import { useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { searchMulti } from '../services/tmdb'
import { searchProfilesByUsername } from '../services/profile'
import { getMyCommunityMemberships, joinCommunity, leaveCommunity, searchCommunities } from '../services/communities'
import { subscribeToFollowing } from '../services/follows'
import { useAuth } from '../context/AuthContext'
import { useSafety } from '../context/SafetyContext'
import { MediaCard } from '../components/media/MediaCard'
import { UserCard } from '../components/people/UserCard'
import { CommunityCard } from '../components/communities/CommunityCard'
import { EmptyState } from '../components/shared/EmptyState'
import { ErrorState } from '../components/shared/ErrorState'
import { PrimaryButton } from '../design-system'

export function SearchResultsPage() {
  const [params] = useSearchParams(); const searchQuery = (params.get('q') || '').trim(); const { user, authLoading } = useAuth(); const safety = useSafety(); const requestId = useRef(0)
  const [section, setSection] = useState('media'); const [mediaTab, setMediaTab] = useState('all'); const [items, setItems] = useState([]); const [users, setUsers] = useState([]); const [communities, setCommunities] = useState([]); const [memberships, setMemberships] = useState([]); const [following, setFollowing] = useState([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(false); const [usersLoading, setUsersLoading] = useState(false); const [communitiesLoading, setCommunitiesLoading] = useState(false); const [pending, setPending] = useState(''); const [error, setError] = useState(''); const [usersError, setUsersError] = useState(''); const [communitiesError, setCommunitiesError] = useState('')
  const loadMedia = async (nextPage, reset, activeRequestId = requestId.current) => { if (searchQuery.length < 2) return; setLoading(true); setError(''); try { const data = await searchMulti(searchQuery, nextPage); if (requestId.current !== activeRequestId) return; const valid = (data.results || []).filter((item) => ['movie', 'tv', 'person'].includes(item.media_type)); setItems((old) => reset ? valid : [...old, ...valid]); setTotalPages(Math.min(data.total_pages || 1, 500)) } catch (e) { if (requestId.current === activeRequestId) setError(e.message) } finally { if (requestId.current === activeRequestId) setLoading(false) } }
  useEffect(() => { const id = ++requestId.current; setItems([]); setUsers([]); setCommunities([]); setError(''); setUsersError(''); setCommunitiesError(''); setPage(1); setSection('media'); setMediaTab('all'); if (searchQuery.length < 2) { setLoading(false); setUsersLoading(false); setCommunitiesLoading(false); return }; loadMedia(1, true, id); setUsersLoading(true); setCommunitiesLoading(true); searchProfilesByUsername(searchQuery, 20).then((result) => { if (requestId.current === id) setUsers(result.filter((item) => !safety.blockedUids.has(item.uid))) }).catch((e) => { if (requestId.current === id) setUsersError(e.message) }).finally(() => { if (requestId.current === id) setUsersLoading(false) }); searchCommunities(searchQuery, 20).then((result) => { if (requestId.current === id) setCommunities(result.filter((item) => !safety.blockedUids.has(item.ownerUid) && !safety.mutedUids.has(item.ownerUid))) }).catch((e) => { if (requestId.current === id) setCommunitiesError(e.message) }).finally(() => { if (requestId.current === id) setCommunitiesLoading(false) }) }, [searchQuery])
  useEffect(() => user?.uid ? subscribeToFollowing(user.uid, setFollowing, () => {}) : undefined, [user?.uid]); useEffect(() => { if (authLoading || !user?.uid) { setMemberships([]); return }; getMyCommunityMemberships(user.uid).then(setMemberships).catch(() => setMemberships([])) }, [authLoading, user?.uid])
  const visible = useMemo(() => mediaTab === 'all' ? items : items.filter((item) => item.media_type === mediaTab), [items, mediaTab]); const followed = useMemo(() => new Set(following.map((item) => item.followingUid)), [following]); const membershipMap = useMemo(() => Object.fromEntries(memberships.map((item) => [item.communityId, item])), [memberships]); const toggleCommunity = async (id) => { if (!user) return; setPending(id); try { if (membershipMap[id]) await leaveCommunity(id); else await joinCommunity(id); setMemberships(await getMyCommunityMemberships(user.uid)) } catch (e) { setCommunitiesError(e.message) } finally { setPending('') } }
  if (searchQuery.length < 2) return <EmptyState title="Arama yap" message="Film, dizi, kullanıcı veya topluluk aramak için en az iki karakter yaz."/>
  return <div className="page-stack"><section className="discover-hero-card genre-hero"><p className="eyebrow">Arama sonuçları</p><h1>“{searchQuery}”</h1></section><div className="media-tabs search-primary-tabs" role="tablist"><button role="tab" aria-selected={section === 'media'} className={section === 'media' ? 'active' : ''} onClick={() => setSection('media')}>Filmler ve Diziler</button><button role="tab" aria-selected={section === 'users'} className={section === 'users' ? 'active' : ''} onClick={() => setSection('users')}>Kullanıcılar</button><button role="tab" aria-selected={section === 'communities'} className={section === 'communities' ? 'active' : ''} onClick={() => setSection('communities')}>Topluluklar</button></div>{section === 'media' ? <><div className="media-tabs" role="tablist">{[['all', 'Tümü'], ['movie', 'Filmler'], ['tv', 'Diziler'], ['person', 'Kişiler']].map(([key, label]) => <button key={key} role="tab" aria-selected={mediaTab === key} className={mediaTab === key ? 'active' : ''} onClick={() => setMediaTab(key)}>{label}</button>)}</div>{error ? <ErrorState message={error}/> : visible.length ? <div className="media-results-grid">{visible.map((item, index) => item.media_type === 'person' ? <article key={`person-${item.id}-${index}`} className="media-card person-card"><div className="media-card-poster">{item.profile_path ? <img src={`https://image.tmdb.org/t/p/w342${item.profile_path}`} alt={item.name}/> : <span>Luma</span>}</div><h3>{item.name}</h3><p>Kişi</p></article> : <MediaCard key={`${item.media_type}-${item.id}-${index}`} item={item}/>)}</div> : !loading ? <EmptyState title="Sonuç bulunamadı" message="Aramana uygun bir yapım bulunamadı."/> : null}{loading ? <div className="list-loading">Sonuçlar yükleniyor…</div> : null}{page < totalPages && !loading ? <PrimaryButton onClick={() => { const next = page + 1; setPage(next); loadMedia(next, false) }}>Daha fazla yükle</PrimaryButton> : null}</> : section === 'users' ? usersLoading ? <div className="list-loading">Kullanıcılar aranıyor…</div> : usersError ? <ErrorState message={usersError}/> : users.length ? <div className="people-grid">{users.map((profile) => <UserCard key={profile.uid} profile={profile} isFollowing={followed.has(profile.uid)}/>)}</div> : <EmptyState title="Kullanıcı bulunamadı" message="Bu kullanıcı adına uygun bir profil bulunamadı."/> : communitiesLoading ? <div className="list-loading">Topluluklar aranıyor…</div> : communitiesError ? <ErrorState message={communitiesError}/> : communities.length ? <div className="community-grid">{communities.map((item) => <CommunityCard key={item.id} community={item} membership={membershipMap[item.id]} pending={pending} onJoin={toggleCommunity} onLeave={toggleCommunity}/>)}</div> : <EmptyState title="Topluluk bulunamadı" message="Bu adla başlayan aktif bir topluluk bulunamadı."/>}</div>
}
