import { useEffect, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { GENRES } from '../config/genres'
import { extractHashtags } from '../services/posts'
import { followUser, subscribeToFollowing } from '../services/follows'
import { useAuth } from '../context/AuthContext'
import { UserAvatar } from './shared/UserAvatar'
import { CommunitySuggestions } from './communities/CommunitySuggestions'

export function RightRail({ users = [], loading, posts = [] }) { const { user } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [following, setFollowing] = useState([]); const [pending, setPending] = useState(''); const hashtags = extractHashtags(posts); useEffect(() => user?.uid ? subscribeToFollowing(user.uid, setFollowing, () => {}) : undefined, [user?.uid]); const followed = new Set(following.map((item) => item.followingUid)); const suggestions = users.filter((profile) => !followed.has(profile.uid || profile.id)).slice(0, 5); const follow = async (profile) => { if (!user) { navigate('/login', { state: { from: location.pathname } }); return } setPending(profile.uid); try { await followUser(user.uid, profile.uid) } finally { setPending('') } }; return <aside className="right-rail"><section className="rail-card"><div className="section-heading compact"><h3>Gündem</h3></div>{hashtags.length ? <div className="topic-list">{hashtags.map((item) => <Link key={item.tag} to={`/hashtag/${encodeURIComponent(item.tag)}`}><span>#{item.tag}</span><small>{item.count} kullanım</small></Link>)}</div> : <p className="rail-empty">Henüz gündem oluşmadı.</p>}</section><section className="rail-card"><div className="section-heading compact"><h3>Keşfedilecek Topluluklar</h3><Link to="/communities">Tümünü gör</Link></div><CommunitySuggestions max={3} compact/></section><section className="rail-card"><div className="section-heading compact"><h3>Önerilen kullanıcılar</h3><Link to="/people">Tümünü gör</Link></div>{loading ? <p className="rail-empty">Kullanıcılar yükleniyor…</p> : suggestions.length ? <div className="user-list">{suggestions.map((profile) => <div key={profile.uid || profile.id} className="rail-user-suggestion"><Link to={`/profile/${encodeURIComponent(profile.username)}`} className="user-row"><UserAvatar profile={profile} name={profile.username} className="avatar"/><div><h4>{profile.username || 'Luma kullanıcısı'}</h4><p>{profile.bio ? `${profile.bio.slice(0, 45)}${profile.bio.length > 45 ? '…' : ''}` : 'Luma üyesi'}</p></div></Link><button type="button" disabled={pending === profile.uid} onClick={() => follow(profile)}>{pending === profile.uid ? '…' : 'Takip et'}</button></div>)}</div> : <div><p className="rail-empty">Henüz önerebileceğimiz başka bir kullanıcı yok.</p><Link className="rail-people-link" to="/people">Kullanıcıları keşfet</Link></div>}</section><section className="rail-card"><div className="section-heading compact"><h3>Türler</h3></div><div className="genre-chip-list">{GENRES.map((genre) => <Link key={genre.slug} to={`/genre/${genre.slug}`}>{genre.label}</Link>)}</div></section></aside> }
