import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { useAuth } from './AuthContext'
import { isBlockedEitherWay, setUserBlocked, setUserMuted, subscribeToBlockedBy, subscribeToBlocks, subscribeToMutes } from '../services/safety'

const SafetyContext=createContext(null)
export function SafetyProvider({children}){const{user,authLoading}=useAuth();const[blocks,setBlocks]=useState([]);const[blockedBy,setBlockedBy]=useState([]);const[mutes,setMutes]=useState([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('')
useEffect(()=>{setBlocks([]);setBlockedBy([]);setMutes([]);setError('');if(authLoading){setLoading(true);return undefined}if(!user?.uid){setLoading(false);return undefined}setLoading(true);let blocksReady=false;let blockedByReady=false;let mutesReady=false;const done=()=>{if(blocksReady&&blockedByReady&&mutesReady)setLoading(false)};const fail=setter=>e=>{setError(e.message);setter(true);done()};const stopBlocks=subscribeToBlocks(user.uid,items=>{setBlocks(items);blocksReady=true;done()},fail(value=>{blocksReady=value}));const stopBlockedBy=subscribeToBlockedBy(user.uid,items=>{setBlockedBy(items);blockedByReady=true;done()},fail(value=>{blockedByReady=value}));const stopMutes=subscribeToMutes(user.uid,items=>{setMutes(items);mutesReady=true;done()},fail(value=>{mutesReady=value}));return()=>{stopBlocks?.();stopBlockedBy?.();stopMutes?.()}},[authLoading,user?.uid])
const ownBlockedUids=useMemo(()=>new Set(blocks.map(item=>item.targetUid)),[blocks]);const blockedByUids=useMemo(()=>new Set(blockedBy.map(item=>item.blockerUid)),[blockedBy]);const blockedUids=useMemo(()=>new Set([...ownBlockedUids,...blockedByUids]),[ownBlockedUids,blockedByUids]);const mutedUids=useMemo(()=>new Set(mutes.map(item=>item.targetUid)),[mutes]);const block=targetUid=>setUserBlocked(user.uid,targetUid,true);const unblock=targetUid=>setUserBlocked(user.uid,targetUid,false);const mute=targetUid=>setUserMuted(user.uid,targetUid,true);const unmute=targetUid=>setUserMuted(user.uid,targetUid,false);const checkBlocked=targetUid=>blockedUids.has(targetUid)?Promise.resolve(true):isBlockedEitherWay(user.uid,targetUid)
return <SafetyContext.Provider value={{blocks,blockedBy,mutes,blockedUids,blockedByUids,mutedUids,loading,error,isBlocked:uid=>ownBlockedUids.has(uid),isBlockedBy:uid=>blockedByUids.has(uid),isMuted:uid=>mutedUids.has(uid),isBlockedEitherWay:checkBlocked,block,unblock,mute,unmute}}>{children}</SafetyContext.Provider>}
export const useSafety=()=>useContext(SafetyContext)
